#!/bin/sh

set -e

PREREQ="fuse"

prereqs () {
        echo "${PREREQ}"
}

case "${1}" in
        prereqs)
                prereqs
                exit 0
                ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/dhcpcd /sbin



exit 0
